config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'books#index'
  
  get '/login', to: 'pages#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, foreign_key: :added_by_id
  has_many :book_events, dependent: :destroy
  after_create :set_cover_image_url
  
  
  validates :title, presence: true
  validates :author, presence: true
  validates :description, presence: true
  validate :upload_cover_image_url
  
  attr_accessor :temporary_cover_image_url
  
  # Add cover image uploader
  mount_uploader :cover_image_url, BookCoverUploader

  
  # Order books by title ascending by default
  default_scope { order(title: :asc) }
  
  def self.get_book_from_lubimy_czytac(url)
    return false unless url.include?('lubimyczytac.pl')
    doc = Nokogiri::HTML(open(url))
    book = self.new
    book.title = doc.css('.grid_5').css('.alpha').css('.omega').css('>h1').try(:text)
    book.author = doc.css('.grid_5').css('.alpha').css('.omega').css('>div>span')[0].try(:text)
    book.description = doc.css('#sBookDescriptionLong')[0].try(:text).try(:squish)
    book.temporary_cover_image_url = doc.css('.nyroModal>img')[0].attributes['src'].value

    book
  end
  
  # returns all unavailable books
  def self.unavailable
    joins(:book_events).where('book_events.return_date' => nil)
  end
  
  # returns array of all available books
  def self.available
    all - unavailable
  end
  
  # returns true if book is available
  def available?
    return true if self.book_events.empty?
    self.book_events.last.returned?
  end
  
  # returns user who has this book
  def current_reader
    return nil if self.available?
    self.book_events.last.user
  end
  
  # Returns book back to libary
  #   Updates last BookEvent return_date with current date
  def return_book
    self.book_events.last.update_attribute(:return_date, Date.today)
  end
  
  # Borrow book by specific user
  # creates new BookEvent
  def borrow_by(user)
    return false if !self.available?
    self.book_events.build(user: user, borrow_date: Date.today).save
  end
  
  # Send reminders in background
  def self.send_reminders
    books = unavailable.where('book_events.borrow_date' => Date.today - 10.days)
    books.each do |book|
      BookMailer.reminder(book).deliver
    end
  end
  
  private 
    def upload_cover_image_url
       errors.add(:base, "Cover image must be added") if self.cover_image_url.file.nil? and self.temporary_cover_image_url.nil?
    end
  
    def set_cover_image_url
      if self.temporary_cover_image_url
        self.update_attribute(:remote_cover_image_url_url, self.temporary_cover_image_url)
        if self.reload.cover_image_url.file.nil?
          self.destroy
        end
      end
    end
end

app/models/book_event.rb
class BookEvent < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :borrow_date, presence: true
  
  def returned?
    !self.return_date.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :name, presence: true
    
    has_many :added_books, class_name: "Book", foreign_key: :added_by_id
    has_many :book_events, -> { where return_date: nil }
    has_many :borrowed_books, through: :book_events, source: :book
    
    # User borrows specific book
    #  (creates new BookEvent with book set to specific book and borrow_date set to current date)
    def borrow_book(book)
        return false if !book.available?
        self.book_events.build(book: book, borrow_date: Date.today).save
    end
    
    
    # Returns user from OmniAuth authentication
    #   (Creates new user when logged in first time)
    def self.from_omniauth(auth_hash)
        user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
        user.name = auth_hash['info']['name']
        user.email = auth_hash['info']['email']
        user.location = auth_hash['info']['location']
        user.image_url = auth_hash['info']['image']
        user.url = auth_hash['info']['urls'][user.provider.capitalize]
        user.save!
        user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :only_logged_in
  before_action :check_authorization, only: [:edit, :destroy]
  
  # /books
  def index
    @borrowed_books = current_user.borrowed_books
    @available_books = Book.available
    @books = Book.all
  end
  
  # /books/:id
  def show
    @book_events = @book.book_events.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end
  
  # /books/new
  def new
    if params[:book_url]
      if @book = Book.get_book_from_lubimy_czytac(params[:book_url])
        flash[:success] = "Getting book details successed"
      else
        flash[:warning] = "Getting book details failed"
        @book = Book.new
      end
    else
      @book = Book.new
    end
  end
  
  # /books/:id/edit
  def edit
  end
  
  # /books
  def create
    @book = current_user.added_books.build(book_params)

    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to @book
    else
      render :new
    end
  end
  
  # /books/:id
  def update
    if params['commit'] == "Borrow"
      if @book.borrow_by(current_user)
        flash[:success] = "You borrowed this book!"
        redirect_back fallback_location: root_path
      end
    elsif params['commit'] == "Return"
      if @book.current_reader == current_user && @book.return_book
        flash[:success] = 'Book was successfully returned'
        redirect_back fallback_location: root_path
      else
        redirect_to root_path
      end
    else
      if @book.update(book_params)
        flash[:success] = 'Book was successfully updated.'
        redirect_to @book
      else
          render :edit
      end
    end
  end
  # /book/:id
  def destroy
    @book.destroy
    flash[:success] = 'Book was successfully destroyed.' 
    redirect_to books_url
  end

  private
    # Make code more DRY
    def set_book
      @book = Book.find(params[:id])
    end
    
    # Strong params
    def book_params
      params.require(:book).permit(:title, :author, :description, :added_by_id, :cover_image_url, :temporary_cover_image_url)
    end
    
    # Only logged in users can access actions, not logged in will be redirected to login path
    def only_logged_in
      redirect_to '/login' if current_user.nil?
    end
    
    # Prevent users from updating/deleting not their books
    def check_authorization
      book = Book.find(params[:id])
      redirect_to root_path unless book.user == current_user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    # /login
    # will show landing page with login button
    def index
        
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    # /auth/:provider
    def create
      begin 
        @user = User.from_omniauth(request.env['omniauth.auth'])
        session[:user_id] = @user.id
        flash[:success] = "Welcome, #{@user.name}!"
      rescue # When athentication fails add warning message
        flash[:warning] = "There was an error while trying to authenticate you..."
      end
      redirect_to root_path
    end
    
    # /logout 
    def destroy
      if current_user
        session.delete(:user_id)
        flash[:success] = 'See you!'
      end
      redirect_to root_path
    end
    
    # used by OmniAuth
    def auth_failure
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/views/books/_book.html.erb
<% view_style ||= :panel         # default view is panel style %>
<% per_row    ||= 4              # there are 4 book in one row by default %>

<% if view_style == :panel %>
<div class="panel panel-default">
  <div class="panel-body">
    
    <div class="row">
      <div class="col-md-1">
        <%= link_to image_tag(book.cover_image_url, alt: book.title, width: '50px', style: "float:left; margin-right:10px"), book_path(book) %>
      </div>
      <div class="col-md-2">
        <strong>Title</strong><br>
        <%= link_to book.title, book_path(book) %>
      </div>
      <div class="col-md-1">
        <strong>Author</strong><br>
        <%= book.author %>
      </div>
      <div class="col-md-7">
        <strong>Description</strong><br>
        <%= truncate book.description, length: 200 %> <%= link_to "Show more", book_path(book) %>
      </div>
      <div class="col-md-1">
        <% if book.available? %>
              <%= form_tag book_path(book), method: :put do %>
                <%= submit_tag 'Borrow', class: 'btn btn-primary btn-sm' %>
              <% end %>
            <% elsif book.current_reader == current_user %>
              <%= form_tag book_path(book), method: :put do %>
                <%= submit_tag 'Return', class: 'btn btn-primary btn-sm' %>
              <% end %>
            <% else %>
              <span class="label label-warning">Not available</span>
            <% end %>
      </div>
    </div>
    
  </div>
</div>

<% elsif view_style == :card %>
    <div class="col-md-<%= 12/per_row %> col-sm-<%= 24/per_row %>" style="padding: 5px; position: relative;">
        <%= link_to image_tag(book.cover_image_url, alt: book.title, class: "img-responsive", width: "100%", height: "100%", title: "#{book.author} - #{book.title}"), book_path(book)%>
        <% if show_button %>
          <div style="position: absolute; bottom: 30px; right: 30px">
          <%= form_tag book_path(book), method: :put do %>
              <%= submit_tag 'Return', class: 'btn btn-primary btn-lg btn-shadow' %>
          <% end %>
          </div>
        <% end %>
    </div>
<% end %>

app/views/books/_books_list.html.erb
<% if view_style == :card %>
<div class="row" style="margin-bottom: 50px">
    <% n = 0 %>
    <% books.each do |book| %>
        <% n += 1 %>
        <%= render book, view_style: :card, show_button: show_button, per_row: per_row %>
        <% if n%per_row == 0 %><div class="clearfix visible-md-block visible-lg-block"></div><% end %>
        <% if n%(per_row/2) == 0 %><div class="clearfix visible-sm-block"></div><% end %>
    <% end %>
</div>
<% elsif view_style == :panel %>
    <%= render books %>
<% end %>

app/views/books/_form.html.erb
<% unless @book.id %>
  <%= form_tag new_book_path, method: 'get', class: 'form-inline' do %>
    <strong style="font-size: 20px">Add link to book on lubimyczytac.pl</strong>
    <div class="form-group form-group-sm">
      <%= text_field_tag :book_url, "", class: 'form-control', placeholder: "http://lubimyczytac.pl/ksiazka/00000/example-book", style: "width: 500px" %>
    </div>
    <%= button_tag 'Get details', name: nil, class: 'btn btn-primary' %>
  <% end %>
  <strong style="font-size: 20px;">...or fill the form</strong>
<% end %>


<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <%= render 'shared/error_messages', object: f.object %>
  <% end %>
  
  <% if @book.temporary_cover_image_url %>
    <%= f.hidden_field :temporary_cover_image_url, value: @book.temporary_cover_image_url %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
            
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
            
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <% if @book.temporary_cover_image_url %>
    <%= image_tag @book.temporary_cover_image_url, alt: @book.title, height: "70px", class: "thumbnail" %>
  <% else %>
  <div class="form-group">
    <%= f.label :cover_image_url, 'Add book image' %>
    <%= f.file_field :cover_image_url %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class='row'>
    <div class="col-md-offset-2 col-md-8">
        <%= link_to 'Show Book', @book %> |
        <%= link_to "Back", :back %>
        <h1>Editing Book</h1>
        <div class='panel panel-default'>
          <div class="panel-body">
              <%= render 'form', book: @book %>
          </div>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<% if @books.any? %>

  <% if @borrowed_books.any? %>
    <h1 class="headline">You borrowed <%= pluralize(@borrowed_books.count, 'book') %></h1>
    <%= render 'books_list', books: @borrowed_books, per_row: 4, view_style: :card, show_button: true %>
  <% end %>

  <% if @available_books.any? %>
    <h1 class="headline">Available Books</h1>
    <%= render 'books_list', books: @available_books, view_style: :panel %>
  <% else %>
    <h1 class="headline">No available books <i class="fa fa-frown-o" aria-hidden="true"></i></h1>
  <% end %>

  <h1 class="headline">All Books</h1>
  <%= render 'books_list', books: @books, per_row: 6, view_style: :card, show_button: false %>
  
<% else %>
  <h1 class="headline">No books in libary <i class="fa fa-frown-o" aria-hidden="true"></i></h1>
  <div class="text-center">
    <%= link_to 'Add first book!', new_book_path, class: "btn btn-success btn-lg" %>
  </div>
<% end %>
<div class="clearfix"></div>

app/views/books/new.html.erb
<div class='row'>
    <div class="col-md-offset-2 col-md-8">
        <%= link_to "Back", :back %>
        <h1>New Book</h1>
        <div class='panel panel-default'>
          <div class="panel-body">
              <%= render 'form', book: @book %>
          </div>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class='row'>
    <div class="col-md-offset-2 col-md-8">
        <%= link_to "Back", books_path %>
        <div class='row book-card'>
            <div class="book-cover">
              <%= image_tag @book.cover_image_url, alt: @book.title, width: '300px' %>
            </div>
            <div class="book-overview">
                <div class='book-title'>
                     <%= @book.title %>
                </div>
                <div class='book-author'><%= @book.author %></div>
                <hr/>
                <div class='book-description'>
                    <%= @book.description %>
                </div>
                <% if @book.user == current_user %>
                    <div class="book-created-by">Added by: You | 
                    <%= link_to 'Edit', edit_book_path(@book) %> | 
                    <%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                <% else %>
                    <div class="book-created-by">Added by: <%= @book.user.name %></div>
                <% end %>
            </div>
        </div>
        <div class="pull-right" style="margin-top: 20px">
            <% if @book.available? %>
                <%= form_tag book_path(@book), method: :put do %>
                    <%= submit_tag 'Borrow', class: 'btn btn-success btn-lg' %>
                <% end %>
            <% elsif @book.current_reader == current_user %>
                <%= form_tag book_path(@book), method: :put do %> 
                    <%= submit_tag 'Return', class: 'btn btn-primary btn-lg' %>
                <% end %>
            <% else %>
               <strong class="label label-warning"><%= @book.current_reader.name %> have this book currently.</strong> 
            <% end %>
        </div>
        <div class="clearfix"></div>
        <h2 style="margin-top: 40px;">Book borrow history</h2>
        <div class='book-history-container'>
            <table class="table">
                <thead>
                    <tr>
                      <th>Borrow Date</th>
                      <th>Return Date</th>
                      <th>Person</th>
                    </tr>
                </thead>
                
                <tbody>
                    <% @book_events.each do |event| %>
                    <tr>
                        <td><%= event.borrow_date %></td>
                        <td><%= event.return_date ? event.return_date : "Currently borrowed" %></td>
                        <td><%= event.user.name %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="pull-right">
            <%= will_paginate @book_events %>
        </div>
    </div>   
</div> 

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "text-center alert alert-#{message_type}", id: "flash") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    LibaryApp | Created by: <%= link_to 'Piotr Borowiec', 'https://bitbucket.org/ptrboro/' %>
</footer>

app/views/layouts/_navbar.html.erb
<header role="banner">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid"> 
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Libary app", root_path, class: "navbar-brand" %> 
            </div>
            <% if current_user %>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Books", books_path %></li>
                    <li><%= link_to 'Add Book', new_book_path %></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                      <li><%= image_tag current_user.image_url, alt: current_user.name, class: "img-circle img-user-avatar" %></li>
                      <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <%= current_user.name %>
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
                        </ul>
                      </li>
                </ul>
            </div>
            <% else %>
                <ul class="nav navbar-nav pull-right">
                    <li><%= link_to 'Login with Google', '/auth/google' %></li>
                </ul>
            <% end %>
        </div> 
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LibaryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>

app/views/pages/index.html.erb
<div class="text-center">
  <h1 class="headline">Welcome in LibaryApp!</h1>
  <h2>Please login:</h2>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default btn-lg"><i class="fa fa-google-plus" aria-hidden="true"></i></button>
    <%= link_to 'Login with Google', '/auth/google', class: "btn btn-default btn-lg" %>
  </div>
  <div style="height: 100px"></div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>